#!/usr/bin/env bash
name="spirv-headers"
version="1.3.261.1"
description="Machine-readable files for the SPIR-V Registry"
source="https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-$version.tar.gz"
depends=""
group="dev.util"


setup(){
	cd $SOURCEDIR
    #mkdir build && cd build
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_SHARED_LIBS=True \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build(){
    cmake --build build
}

package(){
    DESTDIR=$DESTDIR cmake --install build
}

