#!/usr/bin/env bash
name="py3-dbus"
version="1.3.2"
source="https://dbus.freedesktop.org/releases/dbus-python/dbus-python-$version.tar.gz"
description="Python3 bindings for DBUS"
depends="python"
group="dev.python"



setup(){
cd $SOURCEDIR
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
    rm -rf $DESTDIR/usr/lib
}

