#!/usr/bin/env bash
name="lumina"
version="1.6.2"
description="Classes for displaying the contents of SVG files"
source="https://github.com/lumina-desktop/lumina/archive/refs/tags/v${version}.tar.gz"
depends="qt5-base"
builddepend="qmake"
group="lumina.base"


setup () {
	export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	
	qmake lumina.pro CONFIG+=WITH_I18N #LINUX_DISTRO=BasitLinux
}

build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


