#!/usr/bin/env bash
name="webapp-manager"
version="1.3.4"
description="Run websites as if they were apps"
source="https://github.com/linuxmint/webapp-manager/archive/refs/tags/$version.tar.gz"
depends="dconf,xapp"
builddepend=""
group="cinnamon.extra"

setup(){
    cd $SOURCEDIR
}
build(){
    make
}

package(){
	cp -r etc usr "$DESTDIR"
	
	mkdir -p $DESTDIR/usr/lib64/
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
