#!/usr/bin/env bash
name="py3-pathspec"
version="0.12.1"
source="https://github.com/cpburnz/python-pathspec/archive/refs/tags/v${version}.tar.gz"
description="Utility library for gitignore style pattern matching of file paths"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

