#!/usr/bin/env bash
name="libclc"
version="16.0.6"
description="Open source implementation of the library requirements of the OpenCL C programming language"
source="https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/libclc-$version.src.tar.xz"
depends="spirv-llvm-translator"
builddepend="binutils,libmpc,libisl"
group="dev.libs"

setup(){
	cd $SOURCEDIR

    cmake -B $BUILDDIR -G Ninja \
    	-DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DENABLE_RUNTIME_SUBNORMAL=ON \
        -DLLVM_SPIRV=/usr/bin/llvm-spirv
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
