#!/usr/bin/env bash
version="3.2.0"
name="openssl"
depends="glibc"
description="opnssl"
source="https://www.openssl.org/source/${name}-${version}.tar.gz"
groups="dev.libs"
setup()
{
../${name}-${version}/config --prefix=/  \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic \
         no-docs
}
build()
{
	make 
}
package()
{
	cd $BUILDDIR
	make install DESTDIR=$DESTDIR
	cd $DESTDIR
	mkdir -p $DESTDIR/etc
	mkdir -p $DESTDIR/etc/ssl
	
	

	cd $DESTDIR/etc/ssl && {
	    wget -O cacert.pem https://curl.haxx.se/ca/cacert.pem
	    mv -f cacert.pem cert.pem
	    printf '%s\n' "${0##*/}: updated cert.pem"
	}

}


