#!/usr/bin/env bash
name="gdk-pixbuf"
version="2.42.12"
description="gdk-pixbuf Image loading library for GTK+ "
source="https://download.gnome.org/sources/gdk-pixbuf/${version%.*}/gdk-pixbuf-$version.tar.xz"
depends="libjpeg-turbo,shared-mime-info,gi-docgen,libtiff,libpng"
group="x11.libs"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Db_lto=true \
        -Dbuiltin_loaders=all \
        -Dman=false \
        -Dinstalled_tests=false \
        -Dtiff=enabled \
        -Dothers=enabled \
        -Dintrospection=enabled \
        -Dtests=false

}

build(){
	meson compile -C $BUILDDIR
}

package(){
	DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

