#!/usr/bin/env bash
name="hwdata"
version="0.371"
description="Hardware identification and configuration data"
source="https://github.com/vcrhonek/hwdata/archive/refs/tags/v$version.tar.gz"
depends=""
group="sys.apps"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
	cd ../$name-$version
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

