#!/usr/bin/env bash
name="gst-plugins-good"
version="1.22.7"
description="GStreamer plugins"
source="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-${version}.tar.xz"
depends="gstreamer,gst-plugins-base"
group="media.video"


setup(){
	cd $SOURCEDIR
	 meson setup $BUILDDIR --prefix=/usr \
    --libdir=/usr/lib64 \
    -Dqt6=disabled
}
build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
