#!/usr/bin/env bash
name="py3-requests"
version="2.31.0"
source="https://github.com/psf/requests/archive/refs/tags/v${version}.tar.gz"
description="Python HTTP for Humans"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}


