#!/usr/bin/env bash
name="adwaita-icon-theme"
version="45.0"
description="GNOME standard icons"
source="https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/archive/$version/adwaita-icon-theme-$version.tar.gz"
depends="hicolor-icon-theme,librsvg"
group="x11.themes"

setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
