#!/usr/bin/env bash
name="openssl-1.1"
version="1.1.1w"
url="https://www.openssl.org/source/"
description="The Open Source toolkit for Secure Sockets Layer and Transport Layer Security"
source="https://www.openssl.org/source/openssl-$version.tar.gz"
depends=""
group="dev.libs"

# for pod2man
export PATH=$PATH:/usr/bin/core_perl

setup(){
	#cp -prfv $PACKAGEDIR/update-certdata.sh /tmp/bps/build/
	cd $SOURCEDIR
	./Configure --prefix=/usr \
        --openssldir=/etc/ssl \
        --libdir=lib/openssl-1.1\
        shared linux-x86_64
}

build(){
    make depend
    make
}

package(){
    make DESTDIR="${DESTDIR}" install_sw
   
    
    install -m755 -d "$DESTDIR/usr/include/openssl-1.1"
	mv "$DESTDIR/usr/include/openssl" "$DESTDIR/usr/include/openssl-1.1/"
	mv "$DESTDIR/usr/lib/openssl-1.1/libcrypto.so.1.1" "$DESTDIR/usr/lib/"
	mv "$DESTDIR/usr/lib/openssl-1.1/libssl.so.1.1" "$DESTDIR/usr/lib/"
	ln -sf ../libssl.so.1.1 "$DESTDIR/usr/lib/openssl-1.1/libssl.so"
    ln -sf ../libcrypto.so.1.1 "$DESTDIR/usr/lib/openssl-1.1/libcrypto.so"
	mv "$pkgdir/usr/bin/openssl" "$DESTDIR/usr/bin/openssl-1.1"

	# Update includedir in .pc files
	sed -e 's|/include$|/include/openssl-1.1|' -i "$DESTDIR"/usr/lib/openssl-1.1/pkgconfig/*.pc

	rm -rf "$DESTDIR"/{etc,usr/bin/c_rehash}


}

