#!/usr/bin/env bash
name="x11-driver-base"
version="1.0.0"
description="X.Org font aliases "
source=""
depends="xf86-input-elographics,xf86-input-evdev,xf86-input-joystick,xf86-input-keyboard,xf86-input-libinput,xf86-input-mouse,xf86-input-mtrack,xf86-input-synaptics,xf86-input-vmmouse,xf86-input-void,xf86-input-wacom,xf86-video-amdgpu,xf86-video-ast,xf86-video-ati,xf86-video-dummy,xf86-video-fbdev,xf86-video-intel,xf86-video-mga,xf86-video-nouveau,xf86-video-openchrome,xf86-video-qxl,xf86-video-r128,xf86-video-siliconmotion,xf86-video-vboxvideo,xf86-video-vesa,xf86-video-vmware"
group="media.fonts"

setup(){
	echo ""
}

build(){
   echo ""
}

package(){
mkdir -p $DESTDIR/tmp/
touch $DESTDIR/tmp/x11-driver-base
 
}

