#!/usr/bin/env bash
name="py3-consolekit"
version="1.6.0"
description="Easily download, build, install, upgrade, and uninstall Python packages"
source="https://github.com/domdfcoding/consolekit/archive/refs/tags/v${version}.tar.gz"
depends="python"
builddepend="py3-build,py3-installer"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build --wheel --no-isolation
}

package(){
	cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

