#!/usr/bin/env bash
name="xf86-input-keyboard"
version="1.9.0"
description="Xorg keyboard input driver"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-input-keyboard/-/archive/xf86-input-keyboard-$version/xf86-input-keyboard-xf86-input-keyboard-$version.tar.gz"
depends=()
group="x11.drivers"


setup(){
	cd $SOURCEDIR
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}


