#!/usr/bin/env bash
name="sysprof"
version="3.40.1"
description="System-wide profiler for Linux"
source="https://download.gnome.org/sources/sysprof/${version%.*}/sysprof-${version}.tar.xz"
depends="cairo,graphene,hicolor-icon-theme,libex,libunwind"
builddepend="desktop-file-utils,elogind,glib,itstool,json-glib,libadwaita,	libdex,libpanel,libunwind,meson,polkit"
group="gnome.extra"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

