#!/usr/bin/env bash
name="py3-wheel"
version="0.42.0"
url="https://pypi.org/project/wheel/"
description="A built-package format for Python"
source="https://github.com/pypa/wheel/archive/refs/tags/${version}.tar.gz"
depends="python"
builddepend="py3-installer,py3-flit"
group="dev.python"


setup(){
cd $SOURCEDIR
: #  rm -r src/wheel/vendored
}

build(){
    python3 -m build --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

