#!/usr/bin/env bash
name="vala"
version="0.56.3"
description="Compiler for the GObject type system"
source="http://download.gnome.org/sources/vala/0.56/vala-$version.tar.xz"
depends="glib,gcc,graphviz"
group="dev.lang"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-valadoc
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
