#!/usr/bin/env bash
name="wayland-protocols"
version="1.32"
description="Wayland protocol files"
source="https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$version/downloads/wayland-protocols-$version.tar.xz"
depends="wayland"
group="dev.libs"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        -Ddefault_library=both
}

build(){
    ninja -C $BUILDDIR 
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
