#!/usr/bin/env bash
name="dbus"
version="1.15.2"
description="A message bus system, a simple way for applications to talk to each other"
source="https://dbus.freedesktop.org/releases/dbus/dbus-$version.tar.xz"
depends="audit,expat,libcap-ng,elogind,libX11,libunwind"
group="sys.apps"


setup()
{
		mkdir -p /tmp/bps/build/files
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	cd $SOURCEDIR
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
            --sysconfdir=/etc                    \
            --localstatedir=/var                 \
            --runstatedir=/run                   \
            --disable-doxygen-docs               \
            --disable-xml-docs                   \
            --disable-static                     \
            --with-system-pid-file=/run/dbus/dbus.pid \
            --with-x\
            --with-systemduserunitdir=no         \
            --with-systemdsystemunitdir=no       \
            --with-system-socket=/run/dbus/system_bus_socket
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    mkdir -p "$DESTDIR"/etc/init.d "$DESTDIR"/etc/X11/xinit/xinitrc.d/
    install ../files/dbus.initd "$DESTDIR"/etc/init.d/dbus
    install ../files/dbus.xinit "$DESTDIR"/etc/X11/xinit/xinitrc.d/30-dbus-launch.sh
}

