#!/usr/bin/env bash
name="m4"
version="1.4.19"
description="GNU macro processor"
source="https://ftp.gnu.org/gnu/m4/m4-${version}.tar.xz"
depends=""
builddepend=""
group="sys.devel"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

