#!/usr/bin/env bash
name="py3-build"
version="1.2.1"
description="Easily download, build, install, upgrade, and uninstall Python packages"
source="https://github.com/pypa/build/archive/refs/tags/${version}.tar.gz"
depends="python,py3-wheel"
builddepend=""
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build
}

package(){
	cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

