#!/usr/bin/env bash
name="py3-chardet"
version="5.2.0"
description="Python3 module for character encoding auto-detection"
source="https://github.com/chardet/chardet/archive/refs/tags/$version.tar.gz"
depends="python"
builddepend="py3-build,py3-installer,py3-setuptools,py3-wheel"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
