#!/usr/bin/env bash
name="git"
version="2.44.0"
description="the fast distributed version control system"
depends="curl,expat,perl,openssl,libpcre2,grep,zlib"
builddepend="python,xmlto,gettext"
source=("https://mirrors.edge.kernel.org/pub/software/scm/git/git-$version.tar.xz")

group=(dev.vcs)

setup(){
cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_INSTALL_HARDLINKS=1
EOF

	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        ac_cv_lib_curl_curl_global_init=yes \
        ac_cv_snprintf_returns_bogus=no \
        ac_cv_fread_reads_directories=yes
}

build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install
}

