#!/usr/bin/env bash
name="glib"
version="2.78.0"
description="Low-level core library that forms the basis for projects such as GTK+ and GNOME."
source="https://download.gnome.org/sources/glib/2.78/glib-${version}.tar.xz"
depends="libffi,util-linux,libpcre2,zlib"
group="dev.libs"


setup(){
cd $SOURCEDIR
	cp -prfv $dizin/$name/glib.sysconf ./
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64 \
        --default-library both \
        -D glib_debug=disabled \
        -D selinux=disabled \
        -D sysprof=disabled
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install glib.sysconf ${DESTDIR}/etc/sysconf.d/glib
}

