#!/usr/bin/env bash
name="nettle"
version="3.9"
description="A low-level cryptographic library"
source="https://ftp.gnu.org/gnu/nettle/nettle-${version}.tar.gz"
depends="gmp"
group="dev.libs"


setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

