#!/usr/bin/env bash
name="mkfontscale"
version="1.2.2"
description="create an index of scalable font files for X"
source="https://gitlab.freedesktop.org/xorg/app/mkfontscale/-/archive/mkfontscale-$version/mkfontscale-mkfontscale-$version.tar.gz"
depends="freetype,libfontenc"
group="x11.apps"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
