#!/usr/bin/env bash
name="gtk3"
version="3.24.39"
description="Gimp Toolkit"
source="https://download.gnome.org/sources/gtk+/${version:0:4}/gtk+-${version}.tar.xz"
depends="cairo,libXi,libXext,libXfixes,libXcursor,libXdamage,librsvg,at-spi2-core,shared-mime-info,gdk-pixbuf,libxkbcommon,libepoxy,colord,libcloudproviders,dconf,cantarell-fonts,libpng,libXcomposite,libXinerama,glib,libXrandr,pango,wayland"
group="gui.libs"

unset CFLAGS
unset CXXFLAGS

export XDG_DATA_DIRS=/usr/share

setup(){
	mkdir -p /tmp/bps/build/files
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	cd $SOURCEDIR
	patch -Np1 < ../files/nocsd-support.patch
	patch -Np1 < ../files/gtk3-filechooser-icon-view.patch

    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false \
        -D installed_tests=false \
        -D tests=false \
        -D broadway_backend=true \
        -D cloudproviders=true \
        -D colord=yes \
        -D introspection=true \
        -D tracker3=false
}

build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    mkdir -p ${DESTDIR}/etc/sysconf.d
    mkdir -p ${DESTDIR}/etc/profile.d
    echo "export GTK_OVERLAY_SCROLLING=0" > ${DESTDIR}/etc/profile.d/gtk3.sh
    echo "export GDK_CORE_DEVICE_EVENTS=1" >> ${DESTDIR}/etc/profile.d/gtk3.sh
    install ../files/gtk3.sysconf ${DESTDIR}/etc/sysconf.d/gtk3
}

