#!/usr/bin/env bash
version="3.2.14"
name="eudev"
depends="glibc,readline,ncurses,gperf"
description="modül ve sistem iletişimi sağlayan paket"
source="https://github.com/eudev-project/eudev/releases/download/v3.2.14/${name}-${version}.tar.gz"
groups="sys.fs"
setup()
{
	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
	./configure --prefix=/usr \
        --sysconfdir=/etc \
        --exec-prefix=/ \
        --bindir=/bin \
        --with-rootprefix=/ \
        --libdir=/usr/lib64/ \
        --with-rootrundir=/run \
		--with-rootlibexecdir=/usr/lib64/udev \
		--enable-split-usr \
		--disable-selinux \
		--enable-kmod



}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
	mkdir -p ${DESTDIR}/usr/share/initramfs-tools/{hooks,scripts}
  	mkdir -p ${DESTDIR}/usr/share/initramfs-tools/scripts/init-{top,bottom}
  
	
	# OpenRC service
    install -Dm755 ../files/eudev.openrc ${DESTDIR}/etc/init.d/eudev
    # group.d
    install -Dm755 ../files/eudev.groups ${DESTDIR}/etc/group.d/eudev
    # sysconf
    install -Dm755 ../files/eudev.sysconf ${DESTDIR}/etc/sysconf.d/eudev

    install ../files/eudev.hook ${DESTDIR}/usr/share/initramfs-tools/hooks/udev
    install ../files/eudev.init-top ${DESTDIR}/usr/share/initramfs-tools/scripts/init-top/udev
    install ../files/eudev.init-bottom ${DESTDIR}/usr/share/initramfs-tools/scripts/init-bottom/udev
    mkdir -p ${DESTDIR}/etc/udev/rules.d
    touch ${DESTDIR}/etc/udev/rules.d/80-net-name-slot.rules

    	cd ${DESTDIR}
    	mkdir -p bin
    	cd bin
    	ln -s ../sbin/udevadm udevadm
    	ln -s ../sbin/udevd udevd 	
}


