#!/usr/bin/env bash
name="xhost"
version="1.0.9"
description="X server access control program"
source="https://gitlab.freedesktop.org/xorg/app/xhost/-/archive/xhost-$version/xhost-xhost-$version.tar.gz"
depends="libX11"
group="x11.apps"

setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
