#!/usr/bin/env bash
name="util-linux"
version="2.39"
description="Various useful Linux utilities"
source="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v${version}/util-linux-${version}.tar.gz"
depends="libcap-ng,python,eudev"
group="sys.apps"

setup(){
   $SOURCEDIR/configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--bindir=/usr/bin \
	--enable-shared \
	--enable-static \
	--disable-su \
	--disable-runuser \
	--disable-chfn-chsh \
	--disable-login \
	--disable-sulogin \
	--disable-makeinstall-chown \
	--disable-makeinstall-setuid \
	--disable-pylibmount \
	--disable-raw \
	--without-systemd \
	--without-libuser \
	--without-utempter \
	--without-econf \
	--with-python \
	--with-udev
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

