#!/usr/bin/env bash
name="font-ibm-type1"
version="1.0.3"
description=" X.Org IBM Courier font"
source="https://gitlab.freedesktop.org/xorg/font/ibm-type1/-/archive/font-ibm-type1-$version/ibm-type1-font-ibm-type1-$version.tar.gz"
depends="font-util"
group="media.fonts"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

