#!/usr/bin/env bash
name="lzo"
version="2.10"
description="Portable lossless data compression library"
source="https://www.oberhumer.com/opensource/lzo/download/lzo-${version}.tar.gz"
depends=""
builddepend=""

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
    gcc $CXXFLAGS $CFLAGS -fpic -Iinclude/lzo -o minilzo/minilzo.o -c minilzo/minilzo.c
    gcc $LDFLAGS -shared -o libminilzo.so.0 -Wl,-soname,libminilzo.so.0 minilzo/minilzo.o
}

package(){
    make install DESTDIR=$DESTDIR
    install -m 755 libminilzo.so.0 "${DESTDIR}"/usr/lib64
    install -p -m 644 minilzo/minilzo.h ${DESTDIR}/usr/include/lzo
    ln -s libminilzo.so.0 "${DESTDIR}"/usr/lib64/libminilzo.so
}

