#!/usr/bin/env bash
name="xf86-video-qxl"
version="0.1.6"
description="QEMU QXL paravirt video driver"
source="https://www.x.org/releases/individual/driver/xf86-video-qxl-$version.tar.xz"
depends="freetype,spice-protocol"
group="x11.drivers"


setup(){
	cd $SOURCEDIR
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
