#!/usr/bin/env bash
name="enchant"
version="2.8.0"
description="wrapper library for generic spell checking (v2)"
source="https://github.com/AbiWord/enchant/releases/download/v${version}/enchant-${version}.tar.gz"
depends=""
builddepend="dbus,file,gettext,glib,groff"
group="app.text"


setup(){
    cd $SOURCEDIR
    ./configure \
		--prefix=/usr \
		--libdir=/usr/lib64 \
		--disable-static

}
build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install
}

