#!/usr/bin/env bash
name="py3-cssselect2"
version="0.7.0"
description="CSS selectors for Python ElementTree"
source="https://github.com/Kozea/cssselect2/archive/refs/tags/$version.tar.gz"
depends="python,py3-tinycss2,py3-webencodings"
builddepend="py3-flitcore,py3-build,py3-installer,py3-setuptools"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build -nw
}

package(){
	cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

