#!/usr/bin/env bash
name="dbus"
version="1.15.2"
description="A message bus system, a simple way for applications to talk to each other"
source="https://dbus.freedesktop.org/releases/dbus/dbus-$version.tar.xz"
depends="audit,expat,libcap-ng,elogind,libX11"
group="sys.apps"

setup(){
	mkdir -p /tmp/bps/build/files
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	cd $SOURCEDIR
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --localstatedir=/var \
        --sysconfdir=/etc \
        --disable-xml-docs \
        --with-system-pid-file=/run/dbus/dbus.pid \
        --with-x
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    mkdir -p "$DESTDIR"/etc/{passwd,group,sysconf,init,conf}.d "$DESTDIR"/etc/X11/xinit/xinitrc.d/
    echo "messagebus:x:109:" > "$DESTDIR"/etc/group.d/dbus
    echo "messagebus:x:103:109::/nonexistent:/usr/sbin/nologin" > "$DESTDIR"/etc/passwd.d/dbus
    install ../files/dbus.sysconf "$DESTDIR"/etc/sysconf.d/dbus
    install ../files/dbus.initd "$DESTDIR"/etc/init.d/dbus
    install ../files/dbus.confd "$DESTDIR"/etc/conf.d/dbus
    install ../files/dbus.xinit "$DESTDIR"/etc/X11/xinit/xinitrc.d/30-dbus-launch.sh
}

