#!/usr/bin/env bash
name="xf86-input-evdev"
version="2.10.6"
description="Generic Linux input driver"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-input-evdev/-/archive/xf86-input-evdev-$version/xf86-input-evdev-xf86-input-evdev-$version.tar.gz"
depends="mtdev,libevdev,eudev"
group="x11.drivers"


setup(){
	cd $SOURCEDIR
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

