#!/usr/bin/env bash
version="6.6.13"
name="linux-image"
depends=""
description="temel dağıtım kernel dosyası ve moduller"
source=""
groups="sys.base"
setup()
{
	echo ""
	# deb dosyası indirilir http://ftp.tr.debian.org/debian/pool/main/l/linux-signed-amd64/
	cd $SOURCEDIR
	wget -O image.deb http://ftp.tr.debian.org/debian/pool/main/l/linux-signed-amd64/linux-image-6.6.13-amd64_6.6.13-1_amd64.deb
	# ar x indirilen dosya
	ar x image.deb
	# tar -xf data.tar.xz
	tar -xf data.tar.xz
	# find ./ -iname "*" -exec unxz {} \; komutuyla xz açılır
	

	
}
build()
{
	echo ""
}
package()
{
	cd $BUILDDIR
	cp -prfv boot  ${DESTDIR}/
	#cp -prfv $dizin/$name/etc  ${DESTDIR}/
	cp -prfv lib  ${DESTDIR}/
	find ${DESTDIR}/ -iname "*" -exec unxz {} \;
	
}


