#!/usr/bin/env bash
name="gdk-pixbuf"
version="2.42.10"
description="gdk-pixbuf Image loading library for GTK+ "
source="https://download.gnome.org/sources/gdk-pixbuf/${version%.*}/gdk-pixbuf-$version.tar.xz"
depends="libjpeg-turbo,shared-mime-info,gi-docgen,libtiff,libpng"
group="x11.libs"


setup(){
	cd $SOURCEDIR
	cp ${dizin}/${paket}/gdk-pixbuf.sysconf /tmp/bps/build/gdk-pixbuf.sysconf
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false \
        -D installed_tests=false \
        -D tiff=enabled \
        -D tests=false

}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../gdk-pixbuf.sysconf ${DESTDIR}/etc/sysconf.d/gdk-pixbuf
}

