#!/usr/bin/env bash
name="xrandr"
version="1.5.2"
description="Primitive command line interface to RandR extension"
source="https://xorg.freedesktop.org/archive/individual/app/xrandr-$version.tar.xz"
depends="libX11,libXrandr"
group="x11.apps"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}