#!/usr/bin/env bash
name="py3-pygments"
version="2.17.2"
url="https://pypi.org/project/Pygments"
description="Pygments is a syntax highlighting package written in Python."

source="https://github.com/pygments/pygments/archive/refs/tags/${version}.tar.gz"
depends="python"
setup()
{
cd $SOURCEDIR
}
build(){

    python3 -m build --wheel
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
