#!/usr/bin/env bash
name="automake"
version="1.16.5"
description="A GNU tool for automatically configuring source code"
source="https://ftp.gnu.org/gnu/automake/automake-${version}.tar.xz"
depends="autoconf"
group="sys.devel"


setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

