#!/usr/bin/env bash
name="font-xfree86-type1"
version="1.0.4"
description="X.Org XFree86 Type 1 font"
source="https://www.x.org/archive/individual/font/font-xfree86-type1-$version.tar.gz"
depends=""
group="media.fonts"


setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

