#!/usr/bin/env bash
name="py3-setproctitle"
version="1.3.2"
source="https://github.com/dvarrazzo/py-setproctitle/archive/refs/tags/version-${version}.tar.gz"
description="A Python module to customize the process title"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}


