#!/usr/bin/env bash
version="2.39"
name="glibc"
depends=""
description="temel kütüphane"
source="https://ftp.gnu.org/gnu/libc/${name}-${version}.tar.gz"

groups="sys.base"
setup()
{
	../${name}-${version}/configure --prefix=/usr --disable-werror
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
	cd $DESTDIR
	ln -s lib lib64
}


