#!/usr/bin/env bash
name="py3-pygobject"
version="3.43.1"
description="Python bindings for GObject Introspection"
source="https://gitlab.gnome.org/GNOME/pygobject/-/archive/$version/pygobject-$version.tar.gz"
pyver=$(python -c "import sys; print(str( sys.version_info[0]) +\".\"+ str(sys.version_info[1] ))")
depends="python'$pyver',gobject-introspection"
group="dev.python"

cd $SOURCEDIR
setup(){
	echo ""
}

build(){
	cd ../py3-pygobject-$version
    python3 setup.py $BUILDDIR
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}
