#!/usr/bin/env bash
name="font-bh-ttf"
version="1.0.3"
description="X.Org Bigelow & Holmes TrueType fonts"
source="https://gitlab.freedesktop.org/xorg/font/bh-ttf/-/archive/font-bh-ttf-$version/bh-ttf-font-bh-ttf-$version.tar.gz"
depends="font-util"
group="media.fonts"
setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

