#!/usr/bin/env bash
name="gnome-terminal"
version="3.52.0"
description="GNOME terminal emulator application"
source="https://gitlab.gnome.org/GNOME/gnome-terminal/-/archive/${version}/gnome-terminal-${version}.tar.gz"
depends="dconf,gsettings-desktop-schemas,itstool,libpcre2,vte3"
builddepend="libhandy,libxml2"
group="x11.terms"


setup () {

	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Ddocs=false \
		-Dnautilus_extension=false
}

build () {
    ninja -C $BUILDDIR
}

package () {
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

