#!/usr/bin/env bash
version="1.1.0"
name="brotli"
description="Generic-purpose lossless compression algorithm"
source="https://github.com/google/brotli/archive/refs/tags/v$version.tar.gz"
depends="glibc,zlib"
builddepend=""
groups="sys.apps"
setup()
{
	cd $SOURCEDIR
    cmake -B $BUILDDIR -G Ninja \
    	-DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_SHARED_LIBS=True
}
build()
{
	cmake --build $BUILDDIR 
}
package()
{
	DESTDIR=$DESTDIR cmake --install $BUILDDIR	
}


