#!/usr/bin/env bash
name="libfm"
version="1.3.2"
description="Library for file management"
source="https://github.com/lxde/libfm/archive/refs/tags/${version}.tar.gz"
depends="gtk3,pango,intltool,menu-cache"
group="x11.libs"


setup(){
	#cp -prvf $PACKAGEDIR/patches/ /tmp/bps/build/
	cd $SOURCEDIR
	#patch -Np1 -i ../patches/libfm-fixes.patch

    autoreconf -fvi
	 ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
	      --with-gtk=3 \
	      --with-gnu-ld
}

build(){
	sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

