#!/usr/bin/env bash
name="xinit"
version="1.4.2"
description="X Window System initializer xinit"
source="https://gitlab.freedesktop.org/xorg/app/xinit/-/archive/xinit-$version/xinit-xinit-1.4.2.tar.gz"
depends="util-macros,xorgproto,libX11,xorg-server,xterm,xhost,xrdb"
group="x11.apps"


setup(){
	mkdir -p /tmp/bps/build/patches
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	cd $SOURCEDIR
	
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        -sysconfdir=/etc
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    install -m755 -D ../files/xinitrc "$DESTDIR"/etc/X11/xinit/xinitrc
    install -m755 -D ../files/Xsession "$DESTDIR"/etc/X11/xinit/Xsession
    install -m755 ../files/xserverrc "$DESTDIR"/etc/X11/xinit/xserverrc
    install -m755 -D ../files/xinit.sysconf "$DESTDIR"/etc/sysconf.d/xinit
    install -m755 -D ../files/xinit.initd "$DESTDIR"/etc/init.d/xinit
    install -m755 -D ../files/xinit.confd "$DESTDIR"/etc/conf.d/xinit
    install ../files/Xresources "$DESTDIR"/etc/X11/Xresources
    # allow local connections config
    mkdir -p "$DESTDIR"/etc/X11/xinit/xinitrc.d
    echo "#!/bin/sh" > "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
    echo "xhost +local:" >> "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
    chmod 754 "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
}

