#!/usr/bin/env bash
name="py3-pillow"
version="10.2.0"
source="https://github.com/python-pillow/Pillow/archive/refs/tags/${version}.tar.gz"
description="Python Imaging Library"
depends="python3,freetype,lcms2,libtiff,libxcb"
builddepend="git,py3-build,py3-installer,py3-wheel,py3-setuptools,libwebp"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}
