#!/usr/bin/env bash
name="py3-parsing"
version="3.1.2"
description="Python library for creating PEG parsers"
source="https://github.com/pyparsing/pyparsing/releases/download/${version}/pyparsing-${version}.tar.gz"
depends="python"
builddepend=""
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build --skip-dependency-check
}


package(){
    cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

