#!/usr/bin/env bash
name="keyutils"
version="1.6.3"
description="Linux Key Management Utilities"
source="https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-$version.tar.gz"
depends=""
group="sys.apps"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
    make
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
    # fix symlink
    rm -f $DESTDIR/lib64/libkeyutils.so
    ln -s libkeyutils.so.1 $DESTDIR/lib64/libkeyutils.so
}

