#!/usr/bin/env bash
name="xf86-video-ati"
version="22.0.0"
description="ATI video driver"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-video-ati/-/archive/xf86-video-ati-$version/xf86-video-ati-xf86-video-ati-$version.tar.gz"
depends=()
group="x11.drivers"

setup(){
	mkdir -p /tmp/bps/build/patches
    cp ${dizin}/${paket}/patches/* /tmp/bps/build/patches/
	cd $SOURCEDIR
	patch -Np1 -i ../patches/xf86-video-ati-19.1.0-upstream_fixes-1.patch
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
