#!/usr/bin/env bash
name="help2man"
version="1.49.3"
description="Conversion tool to create man files"
source="https://ftp.gnu.org/gnu/help2man/help2man-$version.tar.xz"
depends="perl-locale-gettext"
group="sys.apps"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--libdir=/usr/lib
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

