#!/usr/bin/env bash
name="py3-dill"
version="0.3.8"
description="Python serializer supporting a broader range of types than pickle"
source="https://github.com/uqfoundation/dill/releases/download/$version/dill-$version.tar.gz"
depends="python,py3-wheel"
builddepend="py3-setuptools"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
	python3 -m build
}

package(){
	cd $SOURCEDIR
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

