#!/usr/bin/env bash
name="xf86-input-elographics"
version="1.4.3"
description="Elographics input driver"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-input-elographics/-/archive/xf86-input-elographics-$version/xf86-input-elographics-xf86-input-elographics-$version.tar.gz"
depends=""
group="x11.drivers"

setup(){
	cd $SOURCEDIR
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

