#!/usr/bin/env bash
name="py3-cerberus"
version="1.3.4"
description="Lightweight, extensible data validation library for Python"
depends="python"
group="dev.python"
source="https://github.com/pyeve/cerberus/archive/refs/tags/${version}.tar.gz"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}


