#!/usr/bin/env bash
version="2.69"
name="libcap"
depends="glibc,acl,openssl"
description="shell ve network copy"
source="https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/${name}-${version}.tar.xz"
groups="net.misc"
setup()
{
	
cd $SOURCEDIR
cap_opts=(
    SUDO=""
    prefix=/
    KERNEL_HEADERS=/usr/include
    lib=lib
    RAISE_SETFCAP=no
    #$(use_opt pam PAM_CAP=yes PAM_CAP=no)
    )

}
build()
{
	cd $SOURCEDIR 
	make ${cap_opts[@]} DYNAMIC=yes
    	make ${cap_opts[@]} DYNAMIC=no
}
package()
{
	
	make install DESTDIR=$DESTDIR
	mv $DESTDIR/lib64 $DESTDIR/lib
}


