#!/usr/bin/env bash
name="py3-hotdoc"
version="0.16"
description="A documentation tool micro-framework"
source="https://github.com/hotdoc/hotdoc/archive/refs/tags/$version.tar.gz"
depends="python,json-glib"
group="dev.python"

setup()
{
cd $SOURCEDIR
}

build(){
	python3 -m build --wheel --no-isolation
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
