#!/usr/bin/env bash
name="py3-mako"
version="1.2.4"
description="A super-fast templating language that borrows the best ideas from the existing templating languages."
source="https://pypi.io/packages/source/M/Mako/Mako-${version}.tar.gz"
depends="python,py3-markupsafe"
group="dev.python"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}"  --optimize=1
}

