#!/usr/bin/env bash
name="py3-flit"
version="3.9.0"
url="https://github.com/pypa/flit"
description="Simplified packaging of Python modules"
license="GPLv3"
source="https://github.com/pypa/flit/archive/refs/tags/$version.tar.gz"
depends="python"
builddepend=""
md5sums="f5d670fd1e89950c14e55b7cdc75dcbc"
group="dev.python"
arch="x86_64"

setup(){
	cd $SOURCEDIR
}

build(){
    cur=$PWD
    for dir in . flit_core; do
        cd $dir
        python3 -m build --wheel --skip-dependency-check --no-isolation
        cd $cur
    done
}

package(){
    cur=$PWD
    for dir in . flit_core; do
        cd $dir
        python3 -m installer --destdir="$DESTDIR" dist/*.whl
        cd $cur
    done
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
