#!/usr/bin/env bash
name="xdg-menu"
version="0.7.6.3"
description="automatic generate WM menu from xdg files"
source="https://arch.p5n.pp.ru/~sergej/dl/2018/arch-xdg-menu-$version.tar.gz"
depends="perl,perl-xml-parser"
group="x11.misc"

setup(){
	echo ""
}

build(){
    install -D -m 0755 ../xdg_menu "$DESTDIR"/usr/bin/xdg_menu
    install -D -m 0755 ../xdg_menu_su "$DESTDIR"/usr/bin/xdg_menu_su
    install -D -m 0755 ../update-menus "$DESTDIR"/usr/bin/update-menus
    install -D -m 0644 ../update-menus.conf "$DESTDIR"/etc/update-menus.conf
}

package(){
    mkdir -p "$DESTDIR"/usr/share/desktop-directories/
    cp ../arch-desktop-directories/* "$DESTDIR"/usr/share/desktop-directories/
    mkdir -p "$DESTDIR"/etc/xdg/menus/
    cp ../arch-xdg-menu/* "$DESTDIR"/etc/xdg/menus/
    mkdir -p "$DESTDIR"//var/cache/xdg-menu
}

