#!/usr/bin/env bash
name="cantarell-fonts"
version="0.303.1"
description="Default fontset for GNOME Shell "
source="https://download.gnome.org/sources/cantarell-fonts/${version:0:5}/cantarell-fonts-${version}.tar.xz"
depends=""
group="media.fonts"


setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
	-Duseprebuilt=true
}

build(){
    ninja -C $BUILDDIR 
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

