#!/usr/bin/env bash
version="1.36.1"
name="busybox"
depends="glibc"
description="minimal linux araç paketi static derlenmiş hali"
source="https://busybox.net/downloads/${name}-${version}.tar.bz2"
group="sys.base"
setup()
{
	cd $SOURCEDIR
	make defconfig
	sed -i "s|.*CONFIG_STATIC_LIBGCC .*|CONFIG_STATIC_LIBGCC=y|" .config
	sed -i "s|.*CONFIG_STATIC .*|CONFIG_STATIC=y|" .config
}
build()
{
	make 
}
package()
{
	mkdir -p $DESTDIR/bin
	cp busybox $DESTDIR/bin
}


