#!/usr/bin/env bash
name="py3-pycups"
version="2.0.1"
source=("https://github.com/OpenPrinting/pycups/archive/refs/tags/v$version.tar.gz")
description="Python bindings for cups"
depends="python,cups"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build () {
    python3 setup.py build
}

package () {
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

