#!/usr/bin/env bash
name="font-bitstream-type1"
version="1.0.3"
description="X.Org Bitstream Type 1 fonts "
source="https://gitlab.freedesktop.org/xorg/font/bitstream-type1/-/archive/font-bitstream-type1-$version/bitstream-type1-font-bitstream-type1-$version.tar.gz"
depends="font-util"
group="media.fonts"
setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

