#!/usr/bin/env bash
name="font-cronyx-cyrillic"
version="1.0.3"
description="X.Org Cronyx cyrillic fonts "
source="https://gitlab.freedesktop.org/xorg/font/cronyx-cyrillic/-/archive/font-cronyx-cyrillic-$version/cronyx-cyrillic-font-cronyx-cyrillic-$version.tar.gz"
depends="bdftopcf,font-util"
group="media.fonts"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

