#!/usr/bin/env bash
version="1.3"
name="zlib"
depends="glibc,readline,ncurses"
description="şıkıştırma kütüphanesi"
source="https://zlib.net/current/${name}.tar.gz"
groups="app.arch"
setup()
{
	../${name}-${version}/configure --prefix=/
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


