#!/usr/bin/env bash
name="openrc"
version="0.53"
description="The OpenRC init system"
source="https://github.com/OpenRC/openrc/archive/refs/tags/$version.zip"
depends=""
group="sys.apps,pam"

setup(){
	mkdir -p /tmp/bps/build/files
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	mkdir -p /tmp/bps/build/extras
	cp ${dizin}/${paket}/extras/* /tmp/bps/build/extras/
	cd $SOURCEDIR
    meson setup $BUILDDIR \
        --sysconfdir=/etc \
        --prefix=/ \
        -Ddefault_library=both \
        -Dzsh-completions=true \
        -Dbash-completions=true \
        -Dpam=true \
        -Dpkgconfig=true
}

build(){
    ninja -C build
}

package(){
    export DESTDIR=${DESTDIR}//
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    # disable all services
    rm -f ${DESTDIR}/etc/runlevels/*/*
    rm ${DESTDIR}//etc/init.d/functions.sh
    ln -s ../../lib/rc/sh/functions.sh ${DESTDIR}/etc/init.d/functions.sh
    # install sysconf script
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../files/openrc.sysconf ${DESTDIR}/etc/sysconf.d/openrc
    mkdir -p ${DESTDIR}/etc/group.d
    mkdir -p ${DESTDIR}/etc/passwd.d
    echo "uucp:x:14:" > ${DESTDIR}/etc/group.d/uucp
    echo "uucp:x:10:14:uucp:/var/spool/uucp:/bin/false" > ${DESTDIR}/etc/passwd.d/uucp
    # move /share to /usr/share
    mkdir -p ${DESTDIR}/usr ${DESTDIR}/sbin
    mv ${DESTDIR}/{,usr}/share
    # reboot and poweroff script
    install ../files/reboot ${DESTDIR}/sbin/reboot
    install ../files/poweroff ${DESTDIR}/sbin/poweroff
    ln -s openrc-shutdown ${DESTDIR}/sbin/shutdown
    # install extras
    mkdir -p ${DESTDIR}/usr/libexec
    install ../extras/disable-secondary-gpu.sh ${DESTDIR}/usr/libexec/disable-secondary-gpu
    install ../extras/disable-secondary-gpu.initd ${DESTDIR}/etc/init.d
    install ../extras/backlight-restore.initd ${DESTDIR}/etc/init.d
}

