#!/usr/bin/env bash
name="py3-pdm-pep517"
version="1.1.4"
description="A PEP 517 backend for PDM that supports PEP 621 metadata"
source="https://github.com/pdm-project/pdm-backend/archive/refs/tags/${version}.tar.gz"
depends="py3-tomli-w,python"
group="dev.python"

setup()
{
cp -prfv $PACKAGEDIR/python-pdm-pep517-1.1.2-devendor.patch  $SOURCEDIR/
cd $SOURCEDIR
    patch -Np1 -d pdm-backend-$version -i python-pdm-pep517-1.1.2-devendor.patch

}

build(){
    python3 -m build --wheel --skip-dependency-check --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

