#!/usr/bin/env bash
name="libgedit-gfls"
version="0.1.0"
description="Module for file loading and saving"
source="https://github.com/gedit-technology/libgedit-gfls/archive/${version}/libgedit-gfls-${version}.tar.gz"
depends="glib"
builddepend="gobject-introspection,gtk-doc,meson"
group="gui.libs"


setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        -Db_lto=true \
		-Dgobject_introspection=true \
		-Dgtk_doc=true \

}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

