#!/usr/bin/env bash
name="py3-pyproject-hooks"
version="1.0.0"
url="https://github.com/pypa/build"
description="Low-level library for calling build-backends in 'pyproject.toml'-based project"
source="https://github.com/pypa/pyproject-hooks/archive/refs/tags/v$version.tar.gz"
depends="python"
group="dev.python"

setup(){
cd $SOURCEDIR
#export PYTHONPATH=src/pyproject_hooks
}

build(){
   python3 -m build --wheel --no-isolation
}

package(){
	python3 -m installer --prefix=/usr --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

