#!/usr/bin/env bash
name="expat"
version="2_6_0"
description="An XML parser library"
source="https://github.com/libexpat/libexpat/archive/refs/tags/R_${version}.tar.gz"
#"https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-$version.tar.xz"
depends=""
group="dev.libs"

cd $SOURCEDIR
setup(){
	cd ../$name-$version/$name
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DCMAKE_BUILD_TYPE=None \
        -DEXPAT_BUILD_DOCS=false \
        -W no-dev \
        -B $BUILDDIR
}

build(){
    make -C $BUILDDIR
}

package(){
    make DESTDIR="$DESTDIR" install -C $BUILDDIR
}

