#!/bin/bash
name="libffi"
version="3.4.4"
description="A portable foreign-function interface library. "
source="https://github.com/libffi/libffi/releases/download/v${version}/libffi-${version}.tar.gz"
depends=""
group="dev.libs"

setup(){
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}
build(){
    make
}
package(){
    make install DESTDIR=$DESTDIR
}
