#!/usr/bin/env bash
name="py3-imagesize"
version="1.4.1"
source="https://github.com/shibukawa/imagesize_py/archive/refs/tags/${version}.tar.gz"
description="Getting image size from png/jpeg/jpeg2000/gif file"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

