#!/usr/bin/env bash
name="fakechroot"
version="2.20.1+ds-8"
description="Provide a faked chroot environment without requiring root privileges"
source="https://salsa.debian.org/debian/fakechroot/-/archive/debian/$version/fakechroot-debian-$version.tar.gz"
depends="coreutils"
group="sys.apps"


setup(){
	cd $SOURCEDIR
    for file in ./debian/patches/*.patch ; do
        patch -Np1 -i $file
    done
    
   	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    mkdir -p "${DESTDIR}"/etc/ld.so.conf.d/
    echo "/usr/lib/fakechroot/" > "${DESTDIR}"/etc/ld.so.conf.d/fakechroot.conf
}

