#!/usr/bin/env bash
name="libxslt"
version="1.1.39"
description="XSLT libraries and tools"
source="https://download.gnome.org/sources/libxslt/${version%.*}/libxslt-${version}.tar.xz"
depends="libxml2,zlib,xz-utils"
builddepend="python"
group="dev.libs"


setup(){
    cd $SOURCEDIR
    rm -fv tests/REC/test-10-3.xsl
    NOCONFIGURE=1 ./autogen.sh
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=/usr/lib64/ \
        --without-python
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
