#!/usr/bin/env bash
name="py3-yaml"
version="6.0.1"
description="Python3 bindings for YAML"
source=("https://github.com/yaml/pyyaml/archive/refs/tags/$version.tar.gz")
depends="libyaml,python"
makedepends="py3-wheel,py3-setuptools,py3-build,py3-installer"
group="dev.python"

setup()
{
cd $SOURCEDIR
}

build () {
    python3 -m build --wheel --config-setting=--with-libyaml
}

package () {
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

