#!/usr/bin/env bash
name="xfconf"
version="4.18.3"
description="D-Bus-based configuration storage system"
source="https://archive.xfce.org/src/xfce/xfconf/${version%.*}/xfconf-${version}.tar.bz2"
depends="libxfce4util"
builddepend="intltool,gobject-introspection,vala"
group="xfce.base"

setup () {
	cd $SOURCEDIR
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug

}

build(){
    make
}

package(){
    make DESTDIR=$DESTDIR install
}

