#!/usr/bin/env bash
name="exo"
version="4.18.0"
description="Application library for the Xfce desktop environment"
source="https://archive.xfce.org/src/xfce/exo/${version%.*}/exo-${version}.tar.bz2"
depends="libxfce4ui,libSM,libICE"
builddepend="intltool"
group="xfce.base"

setup () {
	cd $SOURCEDIR
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--libexecdir=/usr/lib64/xfce4 \
		--localstatedir=/var \
		--disable-static \
		--enable-gtk-doc
}

build(){
    make
}

package(){
    make DESTDIR=$DESTDIR install
}

