#!/usr/bin/env bash
version="13.2.0-13"
name="libstdc++-dev"
depends=""
description="temel dağıtım kernel dosyası ve moduller"
source=""
groups="sys.base"
setup()
{
	echo ""
	# deb dosyası indirilirhttp://ftp.tr.debian.org/debian/pool/main/g/gcc-13/
	cd $SOURCEDIR
	wget -O image.deb http://ftp.tr.debian.org/debian/pool/main/g/gcc-13/libstdc%2B%2B-13-dev_13.2.0-13_amd64.deb
	# ar x indirilen dosya
	ar x image.deb
	# tar -xf data.tar.xz
	tar -xf data.tar.xz
	# find ./ -iname "*" -exec unxz {} \; komutuyla xz açılır
	

	
}
build()
{
	echo ""
}
package()
{
	cd $BUILDDIR
	cp -prfv usr/include  ${DESTDIR}/
}


