#!/usr/bin/env bash
name="bash-completion"
version="2.11"
description="Programmable Completion for bash"
source="https://github.com/scop/bash-completion/releases/download/$version/bash-completion-$version.tar.xz"
depends="bash"
builddepend=""
group="app.shell"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

