#!/usr/bin/env bash
name="py3-typogrify"
version="2.0.7"
source="https://github.com/mintchaos/typogrify/archive/refs/tags/$version.tar.gz"
description="A set of Django template filters to make caring about typography on the web a bit easier."
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

