#!/usr/bin/env bash
name="libXau"
version="1.0.10"
description="X.Org X authorization library"
source="https://www.x.org/releases/individual/lib/libXau-${version}.tar.xz"
depends="xorgproto"
group="x11.libs"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-static \
        --enable-shared
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

