#!/usr/bin/env bash
name="elfutils"
version="0.190"
description="Libraries/utilities to handle ELF objects (drop in replacement for libelf)"
source="https://sourceware.org/elfutils/ftp/${version}/elfutils-${version}.tar.bz2"
depends="bzip2,xz-utils,zstd"
group="dev.libs"

setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--enable-shared \
		--enable-static \
		--disable-debuginfod \
		--disable-libdebuginfod \
		--disable-thread-safety \
		--disable-valgrind \
		--disable-nls \
		--program-prefix="eu-" \
		--with-bzlib \
		--with-lzma
}

build(){
	pwd
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

