#!/usr/bin/env bash
version="3.2.14"
name="eudev"
depends="glibc,readline,ncurses"
description="modül ve sistem iletişimi sağlayan paket"
source="https://github.com/eudev-project/eudev/releases/download/v3.2.14/${name}-${version}.tar.gz"
groups="sys.fs"
setup()
{
	cp ${dizin}/${paket}/eudev.hook /tmp/bps/build/
	cp ${dizin}/${paket}/eudev.init-bottom /tmp/bps/build/
	cp ${dizin}/${paket}/eudev.init-top /tmp/bps/build/

	../${name}-${version}/configure --prefix=/           \
            --bindir=/sbin          \
            --sbindir=/sbin         \
            --libdir=/lib       \
            --disable-manpages       \
            --disable-static \
            --disable-selinux \
	    --enable-blkid \
	    --enable-modules \
	    --enable-kmod
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
	mkdir -p ${DESTDIR}/usr/share/initramfs-tools/{hooks,scripts}
  	mkdir -p ${DESTDIR}/usr/share/initramfs-tools/scripts/init-{top,bottom}
  
	
	install ../eudev.hook         ${DESTDIR}/usr/share/initramfs-tools/hooks/udev
    	install ../eudev.init-top         ${DESTDIR}/usr/share/initramfs-tools/scripts/init-top/udev
    	install ../eudev.init-bottom         ${DESTDIR}/usr/share/initramfs-tools/scripts/init-bottom/udev
    	
    	cd ${DESTDIR}
    	mkdir -p bin
    	cd bin
    	ln -s ../sbin/udevadm udevadm
    	ln -s ../sbin/udevd udevd 	
}


