#!/usr/bin/env bash
name="fakeroot"
version="1.31"
description="A fake root environment by means of LD_PRELOAD and SysV IPC (or TCP) trickery"
source="https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_$version.orig.tar.gz"
depends="sed,util-linux,bash"
group="sys.apps"

setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-ipc=sysv
}

build(){
    make
    #cd doc
    #po4a -k 0 --rm-backups --variable "srcdir=../doc/" po4a/po4a.cfg
}

package(){
    make install DESTDIR=$DESTDIR
}

