#!/usr/bin/env bash
name="py3-editables"
version="0.5"
description="library for creating editable wheels"
source="https://github.com/pfmoore/editables/archive/refs/tags/${version}.tar.gz"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
	python3 -m build --wheel --no-isolation
}

package(){
	mkdir -p $DESTDIR/usr/lib64/python3.11
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}


