#!/usr/bin/env bash
name="openrc"
version="0.54"
description="The OpenRC init system"
source="https://github.com/OpenRC/openrc/archive/refs/tags/$version.zip"
depends="bash,glibc,inetutils,libcap,netifrc,pam,psmisc,perl"
builddepend="meson"
group="sys.apps"

setup(){
	mkdir -p /tmp/bps/build/files
	cp ${dizin}/${paket}/files/* /tmp/bps/build/files/
	mkdir -p /tmp/bps/build/extras
	cp ${dizin}/${paket}/extras/* /tmp/bps/build/extras/
	cd $SOURCEDIR
    meson setup $BUILDDIR \
        --sysconfdir=/etc \
        --prefix=/usr \
        --libdir=/lib64 \
        --libexecdir=/lib64 \
        -Dos=Linux \
        -Drootprefix=/usr \
        -Dshell=/bin/bash \
        -Dpam=true \
        -Dsysvinit=true \
        -Dpkgconfig=true \
        -Dzsh-completions=true \
        -Dbash-completions=true \
		-Dnewnet=false \
        -Daudit=disabled \
        -Dselinux=disabled
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install --no-rebuild -C $BUILDDIR
    
    # disable all services
    rm -f ${DESTDIR}/etc/runlevels/*/*
    rm ${DESTDIR}//etc/init.d/functions.sh
    ln -s ../../lib/rc/sh/functions.sh ${DESTDIR}/etc/init.d/functions.sh
    # install sysconf script
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../files/openrc.sysconf ${DESTDIR}/etc/sysconf.d/openrc
    mkdir -p ${DESTDIR}/etc/group.d
    mkdir -p ${DESTDIR}/etc/passwd.d
    echo "uucp:x:14:" > ${DESTDIR}/etc/group.d/uucp
    echo "uucp:x:10:14:uucp:/var/spool/uucp:/bin/false" > ${DESTDIR}/etc/passwd.d/uucp
    # move /share to /usr/share
    mkdir -p ${DESTDIR}/usr ${DESTDIR}/sbin
    mv ${DESTDIR}/{,usr}/share
    # reboot and poweroff script
    install ../files/reboot ${DESTDIR}/sbin/reboot
    install ../files/poweroff ${DESTDIR}/sbin/poweroff
    ln -s openrc-shutdown ${DESTDIR}/sbin/shutdown
    # install extras
    mkdir -p ${DESTDIR}/usr/libexec
    install ../extras/disable-secondary-gpu.sh ${DESTDIR}/usr/libexec/disable-secondary-gpu
    install ../extras/disable-secondary-gpu.initd ${DESTDIR}/etc/init.d
    install ../extras/backlight-restore.initd ${DESTDIR}/etc/init.d
    install ../files/eudev ${DESTDIR}/etc/init.d
    
    # remove init symlink
    rm -v "${DESTDIR}"/usr/bin/init

    install -m755 support/deptree2dot/deptree2dot "${DESTDIR}"/usr/bin/deptree2dot
    
    mkdir -p ${DESTDIR}/usr/libexec
    mv $DESTDIR/lib/* $DESTDIR/usr/libexec/
	rm -rf $DESTDIR/lib
}

