#!/usr/bin/env bash
name="font-adobe-utopia-type1"
version="1.0.4"
description="X.Org Adobe Utopia Type 1 fonts "
source="https://gitlab.freedesktop.org/xorg/font/adobe-utopia-type1/-/archive/font-adobe-utopia-type1-$version/adobe-utopia-type1-font-adobe-utopia-type1-$version.tar.gz"
depends="font-util"
group="media.fonts"
#sudo apt install xutils-dev
setup(){
cd $SOURCEDIR
	   ./autogen.sh
./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

