#!/usr/bin/env bash
name="help2man"
version="1.49.3"
description="Conversion tool to create man files"
source="https://ftp.gnu.org/gnu/help2man/help2man-$version.tar.xz"
depends="perl,perl-locale-gettext"
builddepend=""
group="sys.apps"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--libdir=/usr/lib \
		--localstatedir=/var
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

