#!/usr/bin/env bash
name="py3-ptyprocess"
version="0.7.0"
description="Run a subprocess in a pseudo terminal"
source="https://github.com/pexpect/ptyprocess/archive/refs/tags/${version}.tar.gz"
#source="https://pypi.io/packages/source/p/ptyprocess/ptyprocess-${version}.tar.gz"
depends="python"
builddepend="py3-wheel,py3-pyproject-hooks"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
	python3 -m build --wheel --no-isolation
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

