#!/usr/bin/env bash
name="perl-libwww"
version="6.67"
description="The World-Wide Web library for Perl"
source="https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-$version.tar.gz"
depends="perl"
builddepend=""
group="dev.perl"


setup(){
	cd $SOURCEDIR
    perl Makefile.PL --aliases INSTALLDIRS=vendor
        PREFIX=/usr \
        LIBDIR=/usr/lib64/
}

build(){
    make
}

package(){
    make DESTDIR=$DESTDIR install
}

