#!/usr/bin/env bash
name="xmodmap"
version="1.0.11"
description="utility for modifying keymaps and pointer button mappings in X"
source="https://xorg.freedesktop.org/archive/individual/app/xmodmap-$version.tar.gz"
depends="libX11"
group="x11.apps"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}

