#!/usr/bin/env bash
name="spirv-tools"
version="1.3.261.1"
description="Provides an API and commands for processing SPIR-V modules"
source="https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/sdk-$version.tar.gz"
depends="spirv-headers,gcc"
builddepend="libiconv"
group="dev.util"


setup(){
	cd $SOURCEDIR
    #mkdir build && cd build
    cmake -B build \
        -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DCMAKE_BUILD_TYPE=None \
        -DSPIRV_WERROR=Off \
        -DBUILD_SHARED_LIBS=ON \
        -DSPIRV_TOOLS_BUILD_STATIC=OFF \
        -DSPIRV-Headers_SOURCE_DIR=/usr
}

build(){
    cmake --build build
}

package(){
    DESTDIR=$DESTDIR cmake --install build
}

