#!/usr/bin/env bash
name="py3-setuptools"
version="69.5.1"
url="https://pypi.org/project/setuptools/"
description="Easily download, build, install, upgrade, and uninstall Python packages"
source="https://pypi.io/packages/source/s/setuptools/setuptools-$version.tar.gz"
depends="python"
buildepend="" 
group="dev.python"

export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0


setup(){
    # Fix post-release tag
	  sed -e "/tag_build = .post/d" \
  	    -e "/tag_date = 1/d" \
	      -i setup.cfg
}


build(){
	cd $SOURCEDIR
    python3 setup.py build
}

package(){
	local pyver="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
	# Otherwise it complains that build/scripts-3.12 cannot be found
	# no other changes noted
	mkdir -p build/scripts-"$pyver"
	
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}

