#!/usr/bin/env bash
name="libsass"
version="3.6.5"
description="C/C++ implementation of a Sass compiler"
source="https://github.com/sass/libsass/archive/${version}.tar.gz"
depends=""
group="dev.libs"


setup () {
	cd $SOURCEDIR
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make
}

package () {
    make DESTDIR="$DESTDIR" install
}

