#!/usr/bin/env bash
name="xeyes"
version="1.2.0"
description="X.Org xeyes application"
source="https://gitlab.freedesktop.org/xorg/app/xeyes/-/archive/xeyes-1.2.0/xeyes-xeyes-1.2.0.tar.gz"
depends="libICE,libSM,libXau,libXau,libXext,libXi,libXmu,libXrender,libXt,libxcb"
group="x11.apps"

setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}