#!/usr/bin/env bash
name="bison"
version="3.8.2"
description="The GNU general-purpose parser generator"
source="https://ftp.gnu.org/gnu/bison/bison-$version.tar.xz"
depends=""
group="sys.devel"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

