#!/usr/bin/env bash
name="fribidi"
version="1.0.12"
description="A free implementation of the unicode bidirectional algorithm"
source="https://github.com/fribidi/fribidi/releases/download/v$version/fribidi-$version.tar.xz"
depends=""
group="dev.libs"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
