#!/usr/bin/env bash
name="py3-packaging"
version="23.2"
description="Core utilities for Python3 packages"
source="https://github.com/pypa/packaging/archive/refs/tags/${version}.tar.gz"
depends="python"
builddepend="py3-parsing"
group="dev.python"


#export PYTHONPATH=src/packaging

setup(){
	cd $SOURCEDIR
}

build(){
    python3 -m build -nw
}

package(){
    python3 -m installer --prefix=/usr --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
    mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

