#!/usr/bin/env bash
name="vulkan-loader"
version="1.3.239"
description="Vulkan Installable Client Driver (ICD) Loader"
source="https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v$version.tar.gz"
depends="vulkan-headers,libXrandr,libXrender,libxcb,libX11"
group="media.libs"


setup(){
    cd $SOURCEDIR
    cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_INSTALL_SYSCONFDIR=/etc \
		-DCMAKE_INSTALL_DATADIR=share \
		-DCMAKE_SKIP_RPATH=True \
		-DVULKAN_HEADERS_INSTALL_DIR=/usr
}

build(){
    cmake --build build
}

package(){
    DESTDIR="$DESTDIR" cmake --install build
}
