#!/usr/bin/env bash
name="font-bh-100dpi"
version="1.0.3"
description="X.Org Bigelow & Holmes bitmap fonts"
source="https://gitlab.freedesktop.org/xorg/font/bh-100dpi/-/archive/font-bh-100dpi-$version/bh-100dpi-font-bh-100dpi-$version.tar.gz"
depends="bdftopcf,font-util"
group="media.fonts"

setup(){
cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

