#!/usr/bin/env bash
name="keyutils"
version="1.6.3"
description="Linux Key Management Utilities"
source="https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-$version.tar.gz"
depends=""
builddepend="file"
group="sys.apps"

setup(){
	echo ""
}

build(){
	cd $SOURCEDIR
    make NO_ARLIB=1 \
    	BINDIR='/usr/bin' \
    	SBINDIR='/usr/bin' \
		LIBDIR=/usr/lib \
		USRLIBDIR=/usr/lib \
		VERSION=$version \
		CFLAGS="$CFLAGS"
}

package(){
    make DESTDIR="$DESTDIR" BINDIR='/usr/bin' SBINDIR='/usr/bin' NO_ARLIB=1 LIBDIR=/usr/lib USRLIBDIR=/usr/lib install
}

