#!/usr/bin/env bash
name="setxkbmap"
version="1.3.3"
description="Controls the keyboard layout of a running X server"
source="https://gitlab.freedesktop.org/xorg/app/setxkbmap/-/archive/setxkbmap-$version/setxkbmap-setxkbmap-$version.tar.gz"
depends="libX11,libXau,libXdmcp,libXext,libXrandr,libXrender,libxcb,libxkbfile"
group="x11.apps"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
