#!/usr/bin/env bash
name="python"
version="3.11.8"
description="Python meta package"
source="https://www.python.org/ftp/python/${version}/Python-${version}.tar.xz"
depends="bzip2,expat,gdbm,libffi,libnsl,libxcrypt,openssl,zlib"
builddepend="tcl,sqlite,mpdecimal,tzdata"

group="dev.lang"

setup(){
	cd $SOURCEDIR
	CXX="/usr/bin/g++" \
	./configure --prefix=/usr \
		--enable-ipv6 \
		--enable-loadable-sqlite-extensions \
		--enable-optimizations \
		--enable-shared \
		--with-lto \
		--with-computed-gotos \
		--with-dbmliborder=gdbm:ndbm \
		--with-system-expat \
		--with-system-ffi \
		--with-system-libmpdec \
		--without-ensurepip \
		--with-tzpath=/usr/share/zoneinfo
}

build(){
	make
}

package(){
    make DESTDIR="${DESTDIR}" EXTRA_CFLAGS="$CFLAGS" install
	
	mkdir -p $DESTDIR/usr/lib64
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
	
	ln -s python3 "$DESTDIR"/usr/bin/python
	ln -s python3-config "$DESTDIR"/usr/bin/python-config
}

