#!/usr/bin/env bash
name="py3-markups"
version="4.0.0"
description="Wrapper around various text markups"
source="https://github.com/retext-project/pymarkups/archive/refs/tags/${version}.tar.gz"
depends="python"
builddepend="py3-build,py3-docutils,py3-installer,py3-build,py3-setuptools,py3-wheel"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    
    mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}
