#!/usr/bin/env bash
version="3.7.2"
name="libarchive"
depends="glibc"
description="şıkıştırma kütüphanesi"
source="https://www.libarchive.org/downloads/${name}-${version}.tar.xz"
groups="app.arch"
setup()
{
	../${name}-${version}/configure --prefix=/ 
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


