#!/usr/bin/env bash
name="flex"
version="2.6.4"
description="A tool for generating text-scanning programs"
depends=""
group="sys.devel"
source="https://github.com/westes/flex/archive/refs/tags/v$version.tar.gz"

export PATH=$PATH:$HOME

setup(){
    # create fake makeinfo
    echo "#!/bin/sh" > $HOME/makeinfo
    echo "printf 'makeinfo (GNU texinfo) 5.2\n'" >> $HOME/makeinfo
    chmod +x $HOME/makeinfo
cd $SOURCEDIR
    autoreconf -fvi
   
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
    # remove document build
    rm -rf doc && mkdir doc
    echo "all install:" > doc/Makefile
}

build(){
cd $SOURCEDIR
    make
}

package(){
cd $SOURCEDIR
    make install DESTDIR=$DESTDIR
}

