#!/usr/bin/env bash
name="font-bh-type1"
version="1.0.3"
description="X.Org Bigelow & Holmes Type 1 fonts"
source="https://gitlab.freedesktop.org/xorg/font/bh-type1/-/archive/font-bh-type1-$version/bh-type1-font-bh-type1-$version.tar.gz"
depends="font-util"
group="media.fonts"

setup(){
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
	../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

