#!/usr/bin/env bash
name="colord"
version="1.4.6"
description="System service to accurately color manage input and output devices "
source="https://github.com/hughsie/colord/archive/refs/tags/$version.tar.gz"
depends="lcms2,libgusb,libgudev"
group="x11.misc"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
		-Ddaemon=false \
		-Dsession_example=false \
		-Dbash_completion=false \
		-Dudev_rules=true \
		-Dsystemd=false \
		-Dbash_completion=false \
		-Dlibcolordcompat=true \
		-Dargyllcms_sensor=true \
		-Dsane=false \
		-Dintrospection=false \
		-Dvapi=false \
		-Dprint_profiles=false \
		-Dtests=false \
		-Dinstalled_tests=false \
		-Dman=false \
		-Ddocs=false
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

