#!/usr/bin/env bash
name="sound-theme-freedesktop"
version="0.8"
description="Desktop sound theme from Freedesktop"
source="https://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-$version.tar.bz2"
depends=""
builddepend="intltools"
group="x11.themes"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

