#!/usr/bin/env bash
name="graphene"
version="1.10.8"
description="A thin layer of graphic data types"
source="https://download.gnome.org/sources/graphene/${version%.*}/graphene-${version}.tar.xz"
depends=""
group="media.libs"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dinstalled_tests=false
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

