#!/usr/bin/env bash
name="xorg-xprop"
version="1.2.6"
description="Property displayer for X"
source="https://xorg.freedesktop.org/archive/individual/app/xprop-${version}.tar.xz"
depends="libX11"
group="x11.apps"

setup(){
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}