#!/usr/bin/env bash
version="1.0.8"
name="bzip2"
depends="glibc,readline,ncurses"
description="şıkıştırma kütüphanesi"
source="https://sourceware.org/pub/bzip2/${name}-${version}.tar.gz"
groups="app.arch"
setup()
{
	cd $SOURCEDIR

# Generate relative symlinks
	sed -i \
		-e 's:\$(PREFIX)/man:\$(PREFIX)/share/man:g' \
		-e 's:ln -s -f $(PREFIX)/bin/:ln -s :' \
		Makefile

	# fixup broken version stuff
	sed -i \
		-e "s:1\.0\.4:$version:" \
		bzip2.1 bzip2.txt Makefile-libbz2_so manual.*
		
	
}
build()
{
	 make -f Makefile-libbz2_so all
	 make all
}
package()
{
	cd $SOURCEDIR
	mkdir -p $DESTDIR/bin
	cp -v bzip2-shared $DESTDIR/bin/bzip2
	 mkdir -p $DESTDIR/lib
	cp -av libbz2.so* $DESTDIR/lib
	#ln -sv ../../lib/libbz2.so.1.0 $HOME/rootfs/usr/lib/libbz2.so
	#rm -v $HOME/rootfs/bin/{bunzip2,bzcat,bzip2}
	#ln -sv bzip2 $HOME/rootfs/bin/bunzip2
	#ln -sv bzip2 $HOME/rootfs/bin/bzcat
}


