#!/usr/bin/env bash
name="encodings"
version="1.0.6"
description="X.Org font encodings "
source="https://www.x.org/archive/individual/font/encodings-$version.tar.gz"
depends="mkfontscale"
group="media.fonts"


setup(){
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

