#!/usr/bin/env bash
name="libnghttp2"
version="1.61.0"
description="Framing layer of HTTP/2 is implemented as a reusable C library"
source="https://github.com/nghttp2/nghttp2/releases/download/v${version}/nghttp2-${version}.tar.gz"
depends="glibc"
builddepend="attr,zlib,openssl"
group="net.libs"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--disable-examples \
		--disable-http3 \
		--disable-werror \
		--without-jansson \
		--without-jemalloc \
		--without-libbpf \
		--without-libnghttp3 \
		--without-libngtcp2 \
		--without-libxml2 \
		--without-mruby \
		--without-neverbleed \
		--without-systemd
}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
