#!/usr/bin/env bash
name="vulkan-headers"
version="1.3.269"
description="Vulkan Header files and API registry"
source="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$version.tar.gz"
depends=""
group="dev.util"

setup(){
	cd $SOURCEDIR
    cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
	cmake --build build
}

build(){
    cmake --build build
}

package(){
    DESTDIR="$DESTDIR" cmake --install build
}

