#!/usr/bin/env bash
name="py3-trove-classifiers"
version="2024.1.31"
source="https://github.com/pypa/trove-classifiers/archive/refs/tags/${version}.tar.gz"
description="Canonical source for classifiers on PyPI"
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}


