#!/usr/bin/env bash
name="py3-feedgen"
version="0.9.0"
source="https://github.com/lkiesow/python-feedgen/archive/refs/tags/v$version.tar.gz"
description="feedgen Python 2 and 3 compatibility library "
depends="python"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --prefix=/usr --root="${DESTDIR}" --install-lib=/usr/lib64/python3.11/site-packages --optimize=1 --skip-build
}
