#!/usr/bin/env bash
name="xmlto"
version="0.0.28"
description="Convert xml to many other formats"
source="https://releases.pagure.org/xmlto/xmlto-$version.tar.bz2"
depends="libxslt"
builddepend=""
group="app.text"


setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

