#!/usr/bin/env bash
name='py3-urllib3'
version="2.0.3"
source="https://github.com/urllib3/urllib3/archive/refs/tags/${version}.tar.gz"
description="HTTP library with thread-safe connection pooling, file post, and more"
depends="python"
builddepends="py3-build,py3-installer,py3-setuptools,py3-sphinx,py3-wheel,py3-hatchling"
group="dev.python"

setup()
{
cd $SOURCEDIR
}
build(){
	python3 -m build --wheel --no-isolation

}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
	
	mkdir -p $DESTDIR/usr/lib64/python3.11
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

